FROM python:3.11.0-slim-bullseye

RUN apt-get update
RUN apt-get install -y vim jq fping httpie iftop mtr dnsutils ldnsutils procps htop net-tools iproute2 tcpdump tcptraceroute strace sysstat iperf ngrep
RUN pip install ipython ipdb py-spy
