apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: yatai-with-yatai-deployment
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: yatai-with-yatai-deployment
subjects:
  - kind: ServiceAccount
    name: {{ .Values.yataiSystem.serviceAccountName }}
    namespace: {{ .Values.yataiSystem.namespace }}
