{{- if .Values.bentoDeploymentAllNamespaces }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "yatai-deployment.yatai-with-bento-deployment-rolename" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "yatai-deployment.yatai-with-bento-deployment-rolename" . }}
subjects:
  - kind: ServiceAccount
    name: {{ $.Values.yataiSystem.serviceAccountName }}
    namespace: {{ $.Values.yataiSystem.namespace }}
{{ else }}

{{- range .Values.bentoDeploymentNamespaces }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "yatai-deployment.yatai-with-bento-deployment-rolename" . }}
  namespace: {{ . | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "yatai-deployment.yatai-with-bento-deployment-rolename" . }}
subjects:
  - kind: ServiceAccount
    name: {{ $.Values.yataiSystem.serviceAccountName }}
    namespace: {{ $.Values.yataiSystem.namespace }}
---
{{- end }}

{{- end }}
