{{- range .Values.deploymentNamespaces }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "yatai-deployment.serviceAccountName" $ }}
  namespace: {{ . | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "yatai-deployment.serviceAccountName" $ }}
subjects:
  - kind: ServiceAccount
    name: {{ include "yatai-deployment.serviceAccountName" $ }}
    namespace: {{ $.Release.Namespace }}
{{- end }}
