apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: yatai
  namespace: yatai-builders
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: yatai
subjects:
  - kind: ServiceAccount
    name: yatai
    namespace: yatai-system
