{{- range .Values.bentoDeploymentNamespaces }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: yatai-with-bento-deployment
  namespace: {{ . | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: yatai-with-bento-deployment
subjects:
  - kind: ServiceAccount
    name: {{ $.Values.yataiSystem.serviceAccountName }}
    namespace: {{ $.Values.yataiSystem.namespace }}
{{- end }}
